name: staker

services:
  jwt:
    build:
      context: .
      dockerfile: Dockerfile
    command: util generate-jwt --jwt-path /data/common/jwt.hex
    volumes:
      - ${STAKER_DATA_DIR?}/common:/data/common

  eth1:
    restart: unless-stopped
    depends_on: [jwt]
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      eth1
      start
      --chain ${STAKER_CHAIN_NAME?}
      --jwt-path /data/common/jwt.hex
      --data-dir /data/eth1
      --host 0.0.0.0
      --port 2222
    volumes:
      - ${STAKER_DATA_DIR?}/common:/data/common
      - ${STAKER_DATA_DIR?}/eth1:/data/eth1


  eth2:
    restart: unless-stopped
    depends_on: [eth1]
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      eth2
      start
      --chain ${STAKER_CHAIN_NAME?}
      --jwt-path /data/common/jwt.hex
      --data-dir /data/eth2
      --eth1-url http://eth1:2222
      --host 0.0.0.0
      --port 3333
    volumes:
      - ${STAKER_DATA_DIR?}/common:/data/common
      - ${STAKER_DATA_DIR?}/eth2:/data/eth2

  validator:
    restart: unless-stopped
    depends_on: [eth2]
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      validator
      start
      --chain ${STAKER_CHAIN_NAME?}
      --data-dir /data/eth2
      --eth2-url http://eth2:3333
      --host 0.0.0.0
      --port 4444
      --suggested-fee-recipient
      ${STAKER_SUGGESTED_FEE_RECIPIENT_ADDRESS?}

    volumes:
      - ${STAKER_DATA_DIR?}/eth2:/data/eth2
