name: staker

services:
  jwt:
    build:
      context: .
      dockerfile: Dockerfile
    command: util generate-jwt --jwt-path /data/common/jwt.hex
    volumes:
      - ./data/common:/data/common

  eth1:
    depends_on: [jwt]
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      eth1
      start
      --jwt-path /data/common/jwt.hex
      --data-dir /data/eth1
      --port 9000
    volumes:
      - ./data/common:/data/common
      - ./data/eth1:/data/eth1


  eth2:
    depends_on: [eth1]
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      eth2
      start
      --jwt-path /data/common/jwt.hex
      --data-dir /data/eth2 --eth1-url http://eth1:9000
    volumes:
      - ./data/common:/data/common
      - ./data/eth2:/data/eth2
